name: Notify on API change

on:
  push:
    branches:
      - master
    paths:
      - "**.html"
jobs:
  notify_changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: send custom message with args
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            The Telegram Bot API Documentation has changed in the last hour. 
            
            You can compare it to the previous version here: https://github.com/code1mountain/telegram-bot-api-log
